### ISSUE TITLE
[EPIC] Adding Tags to Problems

### ISSUE THREAD

**Issue by nvatuan** [BKDN-University/bkdnOJ-v2#56]
_Skipping some stages since we are rushing_

# BUSINESS
## Actors
- Normal User
- Staff, Admin

## Problems
- Staff have difficults to organize contests by Topic, since there is no way to group problems with the same topic together.
- Users who need to improve on certain Topic has no way to look for problems of certain kinds.
- Users and Staffs have no way to tag Problems.

## Background
- Codeforces and other OJ are implementing their own taggings systems, we may look into them for references.

## Goals
- Each problems need to have a list of tags, keywords so that they are better organized, searchable, easier to be identified.
- Staffs can manually tag, untag problems
- Users can see tags of problems if they are viewable, can search problem by tags

## Value
- Problem tags will FURTHER improve problem management
- With Problem Tags, more features will be enable, such as Problem Recommendation, User Strength Analyzer,...
- Better managing

# USER EXPERIENCE
*Below lists User Stories, User Journeys. From which screen, with which action, users get taken to where and what will be achieved?*
### View tags of problems
- At Problem List view, each problem should have their tags list along their title

### Search Problems by Tags
- At Problem List view, there should be a filter or form, for user to search Problems by tags

### View tags of Problem in Problem Detail
- At Problem Detail screen, user should be able to view its tags too.

### Can set tags of Problem
- Staff can set or unset tags for their own Problems

### Can see/edit Problem Tags on system 
- Can CRUD tags object on system

# ARCHITECTURE DESIGN

- TDD: Link Here
- DB
![image](https://github.com/bkdnOJv2/bkdnOJ-v2/assets/24392632/119c557e-15fe-4b8c-82a8-44cb30f47612)

<p style="color: red;"> Convert to Urgent, we'll skip some TDD and UI design here </p>

# BREAK TASK | 2023-06-05
### DB:
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/39

#### Problems View:
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/36
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/37
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/38
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/45

#### Problem Tags View:
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/40
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/41
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/42
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/43
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-backend/issues/44

### Normal User screens:
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-frontend/issues/31
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-frontend/issues/32
- [ ] https://github.com/bkdnOJv2/bkdnOJ-reborn-frontend/issues/33

### Staff screens:
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-frontend/issues/34

### Admin screens:
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-frontend/issues/35
- [x] https://github.com/bkdnOJv2/bkdnOJ-reborn-frontend/issues/36

# CODING | 2023-06-05
